name: Bug Report
description: Report a bug to help us improve the powercloud/tritonserver image.
title: "[Tritonserver Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A clear and concise summary of the bug.
    validations:
      required: true
  - type: input
    id: affected-version
    attributes:
      label: Affected Version
      description: Which version of the `powercloud/tritonserver` image are you using?
      placeholder: e.g., quay.io/powercloud/tritonserver:2.59.0
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Please provide a minimal, reproducible example. Include any model configuration files and the command used to run the server.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened? Please include the full error message, stack trace, and any relevant server logs.
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched the existing issues to ensure this is not a duplicate.
          required: true
        - label: I have provided a clear summary and details.
          required: true
        - label: (For Bug Reports) I have included steps to reproduce the issue.
          required: true
        - label: I have attached any necessary logs, configuration files, or other context.
          required: true
